"""add drift execution venue to auto_trade_configs

Revision ID: 1caea4056e92
Revises: 5641c9055934
Create Date: 2026-05-04 17:41:11.777016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1caea4056e92'
down_revision: Union[str, Sequence[str], None] = '5641c9055934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_trade_configs', sa.Column('execution_venue', sa.String(length=20), nullable=False, server_default='bybit_demo'))
    op.add_column('auto_trade_configs', sa.Column('solana_private_key', sa.Text(), nullable=True))
    op.add_column('auto_trade_configs', sa.Column('solana_rpc_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_trade_configs', 'solana_rpc_url')
    op.drop_column('auto_trade_configs', 'solana_private_key')
    op.drop_column('auto_trade_configs', 'execution_venue')
    # ### end Alembic commands ###
