"""add auto_trade_configs and auto_trade_logs tables

Revision ID: 32ce952608e0
Revises: 02aae007198d
Create Date: 2026-05-04 06:27:12.349383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ce952608e0'
down_revision: Union[str, Sequence[str], None] = '02aae007198d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_trade_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('testnet', sa.Boolean(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('position_size_pct', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('tp_pct', sa.Float(), nullable=False),
    sa.Column('sl_pct', sa.Float(), nullable=False),
    sa.Column('daily_loss_limit', sa.Float(), nullable=False),
    sa.Column('symbols', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_trade_configs_user_id'), 'auto_trade_configs', ['user_id'], unique=True)
    op.create_table('auto_trade_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_trade_logs_user_id'), 'auto_trade_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_positions_user_ticker'), table_name='positions')
    op.drop_index(op.f('ix_signals_user_created'), table_name='signals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_signals_user_created'), 'signals', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_positions_user_ticker'), 'positions', ['user_id', 'ticker'], unique=False)
    op.drop_index(op.f('ix_auto_trade_logs_user_id'), table_name='auto_trade_logs')
    op.drop_table('auto_trade_logs')
    op.drop_index(op.f('ix_auto_trade_configs_user_id'), table_name='auto_trade_configs')
    op.drop_table('auto_trade_configs')
    # ### end Alembic commands ###
