"""add demo column to auto_trade_configs

Revision ID: 5641c9055934
Revises: 32ce952608e0
Create Date: 2026-05-04 08:43:06.367937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5641c9055934'
down_revision: Union[str, Sequence[str], None] = '32ce952608e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_trade_configs', sa.Column('demo', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_trade_configs', 'demo')
    # ### end Alembic commands ###
