"""add bybit keys to users

Revision ID: 8f5683f7904f
Revises: b7fa7dfcfb77
Create Date: 2026-05-02 16:54:18.108890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5683f7904f'
down_revision: Union[str, Sequence[str], None] = 'b7fa7dfcfb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bybit_api_key', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('bybit_api_secret', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bybit_api_secret')
    op.drop_column('users', 'bybit_api_key')
    # ### end Alembic commands ###
