"""add bybit testnet keys to users

Revision ID: cdffb41d4526
Revises: 8f5683f7904f
Create Date: 2026-05-02 17:18:39.632353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdffb41d4526'
down_revision: Union[str, Sequence[str], None] = '8f5683f7904f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bybit_testnet_key', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('bybit_testnet_secret', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bybit_testnet_secret')
    op.drop_column('users', 'bybit_testnet_key')
    # ### end Alembic commands ###
